using System.Numerics;

List<BigInteger> distinctTerms = new List<BigInteger>();

BigInteger result = 0;

int limitNumber = 100;

for(int a = 2; a <= limitNumber; a++)
{
    for(int b = 2; b <= limitNumber; b++)
    {
        result = BigIntPow(a, b);
        if(!distinctTerms.Contains(result))
            distinctTerms.Add(result);
    }
}

Console.WriteLine("There are {0} distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100", distinctTerms.Count); 

BigInteger BigIntPow(BigInteger a, int b)
{
    BigInteger result = a;

    for (int i = 2; i <= b; i++)
        result = result * a;

    return result;
}